### PR TITLE
PilotController, Drivetrain, and robot.java

### LINKED ISSUE #30: Shifting gear and initial state
Currently, when we start our robot, our drivetrain gear is set to unknown. Last year this was because it would allow us to immediately set the gear, but this year it doesn't get set until teleop, meaning in auton our gear is technically unknown.

I'm not sure if this is causing issues now, but it could lead to undefined behaviour

### LINKED ISSUE #31: Limelight infrastructure in Robot
We currently have a good bit of unused limelight configuration stuff for the shuffleboard in the main robot. If we don't plan on using the limelight at all, then this should be removed, and if we will want to use it it should probably be cleaned a little bit or stored somewhere else

### LINKED ISSUE #38: Dead Code needs to be removed
The majority of the time today was spent trying to understand why when we were changing the motor inversion it wasn't being applied. The reason was that we had two constructors for the Launcher, but only one of them set the inversion and that wasn't the constructor we were calling. We should not have code that we never call. I noticed a bunch of other methods that basically aren't ever called. These methods should be removed.

### PR DESCRIPTION
**Pull request by HannahStrimpel**
I got rid of unused import in robot.java. I also changed Drivetrain so we begin in low gear instead of it being unknown. Josh had created an issue about this. In pilotcontroller, I got rid of the unused constructor.

### CODE REVIEW

**Review by coverbeek — COMMENTED** [review]
I know I asked for dead code to be removed, but isn't the shuffleboard stuff in there for a reason? I thought on Friday it was asserted that this stuff worked?

**Review by coverbeek — CHANGES_REQUESTED** [review]
I thought I mentioned calling shiftGear in Init, but perhaps I didn't. I think we need to move that call to Init.

**Review by JooshO — APPROVED** [review]
I think with that last change this looks good, I'd like another review on it though

**Review by MikasaSucasa — APPROVED** [review]
Looks good to me. Make sure that you understand why there is an init function rather than just utilizing a constructor (even if it would still function). @coverbeek I think the changes look good but you mention the shuffleboard items and was unsure what you wanted. I will merge tomorrow after work if you don't get to it.

**Pull request closed without merging**
